version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
      - "8080:8080"
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finance-tracker
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - docker/db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: